# Generated by Django 5.0.7 on 2024-07-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctions",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
