# Generated by Django 5.0.7 on 2024-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_auctions_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctions", name="image", field=models.URLField(default=""),
        ),
    ]
