# Generated by Django 5.0.7 on 2024-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_auctions_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctions",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
