# Generated by Django 5.0.7 on 2024-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_auctions_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctions",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="auctions",
            name="image",
            field=models.URLField(blank=True, default=""),
        ),
    ]
