# Generated by Django 5.0.7 on 2024-07-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_auctions_active_alter_auctions_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctions",
            name="description",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
