# Generated by Django 5.0.7 on 2024-07-24 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_auctions_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctions",
            name="watchlist",
            field=models.ManyToManyField(
                related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
